version: '3'
services:
  php:
    container_name: vue_laravel_docker_php
    build: ./docker/php
    volumes:
    - ./web:/var/www
    
  nginx:
    image: nginx
    container_name: vue_laravel_docker_nginx
    ports:
    - 80:80
    volumes:
    - ./web:/var/www
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php
  
  db:
    image: mysql:8.0
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    ports:
      - ${DB_PORT}:3306